# Generated by Django 4.0.5 on 2022-06-30 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.PositiveBigIntegerField(default=318126512000, help_text='Enter your roll number (length-12) : <em>(318126xxxxxx)</em> format', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(318126512999), django.core.validators.RegexValidator('^\\d{1,12}')], verbose_name='Roll number')),
                ('name', models.CharField(max_length=50)),
                ('class_signature', models.CharField(choices=[('ECE-A', 'ECE-A'), ('ECE-B', 'ECE-B'), ('CSE-A', 'CSE-A'), ('CSE-B', 'CSE-B'), ('EEE-A', 'EEE-A')], default='ECE-A', max_length=5)),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='format: <em>x.xx</em> Eg:8.85', max_digits=4, validators=[django.core.validators.RegexValidator('^\\d{1}\\.\\d{1,2}$')])),
                ('year', models.CharField(choices=[('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth')], default='I', max_length=4)),
            ],
        ),
    ]
