# Generated by Django 4.0.5 on 2022-07-01 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Enter according to the format x.xx'}, help_text='format: <em>x.xx</em> Eg:8.85', max_digits=4, validators=[django.core.validators.RegexValidator('^\\d{1}\\.\\d{1,2}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_signature',
            field=models.CharField(choices=[('ECE-A', 'ECE-A'), ('ECE-B', 'ECE-B'), ('CSE-A', 'CSE-A'), ('CSE-B', 'CSE-B'), ('EEE-A', 'EEE-A')], default='ECE-A', max_length=5, verbose_name='Branch and Section'),
        ),
    ]
